# This file contains the configuration for the package
redirectUrl = "http://localhost:5000"

# Should we filter specific playlists?
filter = false

# Enter a list of playlists that you would like to port
playlistsToFilter = ["Vibe","Drive"]


######### YOUTUBE #################3
baseYoutubeSearch = "https://www.youtube.com/results?search_query="
baseYoutubeVideoLink = "https://www.youtube.com/watch?v="
youtubeMaxEntriesInSearch = 5 
youtubeMinViewsThresholdMills = 1 